/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package main.java.com.fangming.news;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int attachment_blue=0x7f060000;
        public static final int black=0x7f060001;
        public static final int blue=0x7f060002;
        public static final int blue_bar=0x7f060003;
        public static final int blue_black=0x7f060004;
        public static final int blue_item=0x7f060005;
        public static final int blue_split=0x7f060006;
        public static final int blue_title=0x7f060007;
        public static final int border_color=0x7f060008;
        public static final int btnother=0x7f060009;
        public static final int child_divider_list=0x7f06000a;
        public static final int child_even_list=0x7f06000b;
        public static final int child_uneven_list=0x7f06000c;
        public static final int colorAccent=0x7f06000d;
        public static final int colorPrimary=0x7f06000e;
        public static final int colorPrimaryDark=0x7f06000f;
        public static final int comm_list_item_divider_color=0x7f060010;
        public static final int contentGrey=0x7f060011;
        public static final int current_day_color=0x7f060012;
        public static final int date=0x7f060013;
        public static final int date_background=0x7f060014;
        public static final int day_color=0x7f060015;
        public static final int deepGrey=0x7f060016;
        public static final int dividerGrey=0x7f060017;
        public static final int even=0x7f060018;
        public static final int gray_operator_bar_bg=0x7f060019;
        public static final int green=0x7f06001a;
        public static final int green_black=0x7f06001b;
        public static final int grey=0x7f06001c;
        public static final int grey2=0x7f06001d;
        public static final int grey_bg=0x7f06001e;
        public static final int grey_light=0x7f06001f;
        public static final int grouplistitem=0x7f060020;
        public static final int holo_blue=0x7f060021;
        public static final int home_line=0x7f060022;
        public static final int homeblue=0x7f060023;
        public static final int homedblue=0x7f060024;
        public static final int homegreen=0x7f060025;
        public static final int homeorange=0x7f060026;
        public static final int inner_grid_color=0x7f060027;
        public static final int item_selected_grey=0x7f060028;
        public static final int layout_grey=0x7f060029;
        public static final int lefttextcolor=0x7f06002a;
        public static final int lightBlue=0x7f06002b;
        public static final int lightFBlue=0x7f06002c;
        public static final int lightFRed=0x7f06002d;
        public static final int lightGrey=0x7f06002e;
        public static final int lightblue=0x7f06002f;
        public static final int line_color=0x7f060030;
        public static final int linen=0x7f060031;
        public static final int logininput=0x7f060032;
        public static final int map_select_bg=0x7f060033;
        public static final int map_top_back_bg=0x7f060034;
        public static final int me_activity_lineColor=0x7f060035;
        public static final int mt_blue=0x7f060036;
        public static final int mt_host_bg=0x7f060037;
        public static final int odd=0x7f060038;
        public static final int operator_group_title_tv=0x7f060039;
        public static final int otherbg=0x7f06003a;
        public static final int othertxt=0x7f06003b;
        public static final int possible_result_points=0x7f06003c;
        public static final int prev_next_month_day_color=0x7f06003d;
        public static final int readGrey=0x7f06003e;
        public static final int recording_time_elapsed_text=0x7f06003f;
        public static final int recording_time_remaining_text=0x7f060040;
        public static final int recordremind_background=0x7f060041;
        public static final int recordremindtext_color=0x7f060042;
        public static final int red=0x7f060043;
        public static final int result_view=0x7f060044;
        public static final int selectdeparment=0x7f060045;
        public static final int specialgreen=0x7f060046;
        public static final int split_blue=0x7f060047;
        public static final int split_grey=0x7f060048;
        public static final int sunday_saturday_color=0x7f060049;
        public static final int sunday_saturday_prev_next_month_day_color=0x7f06004a;
        public static final int table_text=0x7f06004b;
        public static final int text_color=0x7f06004c;
        public static final int titleBlack=0x7f06004d;
        public static final int title_bg=0x7f06004e;
        public static final int title_color=0x7f06004f;
        public static final int title_operater=0x7f060050;
        public static final int today_background_color=0x7f060051;
        public static final int today_color=0x7f060052;
        public static final int top_bule=0x7f060053;
        public static final int top_bule_bj=0x7f060054;
        public static final int translate=0x7f060055;
        public static final int transparent=0x7f060056;
        public static final int unReadRed=0x7f060057;
        public static final int viewfinder_mask=0x7f060058;
        public static final int week_today=0x7f060059;
        public static final int weekname_color=0x7f06005a;
        public static final int white=0x7f06005b;
        public static final int yellow=0x7f06005c;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int back_title=0x7f020000;
        public static final int bt_nobgd=0x7f020001;
        public static final int channel_glide=0x7f020002;
        public static final int channel_glide_day_bg=0x7f020003;
        public static final int channel_glide_press=0x7f020004;
        public static final int conner_left=0x7f020005;
        public static final int conner_left2=0x7f020006;
        public static final int corners_bg=0x7f020007;
        public static final int corners_fourbg=0x7f020008;
        public static final int dot1=0x7f020009;
        public static final int dot2=0x7f02000a;
        public static final int guid_ty_bg=0x7f02000b;
        public static final int ic_launcher=0x7f02000c;
        public static final int ic_menu_deal_off=0x7f02000d;
        public static final int ic_menu_deal_on=0x7f02000e;
        public static final int ic_menu_home=0x7f02000f;
        public static final int ic_menu_more=0x7f020010;
        public static final int ic_menu_more_off=0x7f020011;
        public static final int ic_menu_more_on=0x7f020012;
        public static final int ic_menu_poi_off=0x7f020013;
        public static final int ic_menu_poi_on=0x7f020014;
        public static final int ic_menu_store=0x7f020015;
        public static final int ic_menu_user=0x7f020016;
        public static final int ic_menu_user_off=0x7f020017;
        public static final int ic_menu_user_on=0x7f020018;
        public static final int index_category_indicator_nor=0x7f020019;
        public static final int index_category_indicator_selected=0x7f02001a;
        public static final int list_item_selector=0x7f02001b;
        public static final int menu_topbar_level_selector=0x7f02001c;
        public static final int progress_bar_states=0x7f02001d;
        public static final int progressbar=0x7f02001e;
        public static final int tab_dot=0x7f02001f;
        public static final int vipager_doc_select=0x7f020020;
    }
    public static final class id {
        public static final int btn_home=0x7f090009;
        public static final int btn_left_back=0x7f09001b;
        public static final int btn_right_cmd=0x7f09001c;
        public static final int btn_update=0x7f09000d;
        public static final int button_more_columns=0x7f090006;
        public static final int drawer_layout=0x7f090001;
        public static final int file_icon=0x7f09000b;
        public static final int file_name=0x7f09000c;
        public static final int file_path=0x7f09000a;
        public static final int image1=0x7f090015;
        public static final int image2=0x7f090016;
        public static final int image3=0x7f090017;
        public static final int image_right=0x7f090011;
        public static final int layout_image=0x7f090014;
        public static final int layout_title=0x7f090000;
        public static final int letf_title=0x7f09000f;
        public static final int mColumnHorizontalScrollView=0x7f090003;
        public static final int mRadioGroup_content=0x7f090004;
        public static final int mViewPager=0x7f090007;
        public static final int mlistview=0x7f09000e;
        public static final int rl_column=0x7f090002;
        public static final int shade_right=0x7f090005;
        public static final int titleview=0x7f090008;
        public static final int tv_plnumber=0x7f090019;
        public static final int tv_pro=0x7f090013;
        public static final int tv_source=0x7f090018;
        public static final int tv_time=0x7f09001a;
        public static final int tv_title=0x7f090012;
        public static final int user_image=0x7f090010;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
        public static final int file_browser_activity=0x7f040001;
        public static final int file_item=0x7f040002;
        public static final int fragment_news=0x7f040003;
        public static final int include_action_bar=0x7f040004;
        public static final int left_layout=0x7f040005;
        public static final int newsadapter_item=0x7f040006;
        public static final int titile_bar=0x7f040007;
    }
    public static final class mipmap {
        public static final int channel_rightblock=0x7f030000;
        public static final int doc=0x7f030001;
        public static final int folder=0x7f030002;
        public static final int gc_user_center=0x7f030003;
        public static final int ic_launcher=0x7f030004;
        public static final int ic_menu_user_off=0x7f030005;
        public static final int ic_menu_user_on=0x7f030006;
        public static final int left_js=0x7f030007;
        public static final int title=0x7f030008;
        public static final int title_back=0x7f030009;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int cancel_back=0x7f070001;
        public static final int file_cannotopen=0x7f070002;
        public static final int hello_world=0x7f070003;
        public static final int open_main_page=0x7f070004;
        public static final int share_app=0x7f070005;
    }
    public static final class style {
        public static final int AppBaseTheme=0x7f080000;
        public static final int AppTheme=0x7f080001;
        public static final int backbtn=0x7f080002;
        public static final int ic_category_text=0x7f080003;
        public static final int item_sj_add=0x7f080004;
        public static final int item_sj_storename=0x7f080005;
        public static final int leftlayout_list_tv=0x7f080006;
        public static final int listview5_style=0x7f080007;
        public static final int sy_tablehost=0x7f080008;
    }
}
